// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJtJt4YYo5DFB6bC0PLG8b-U6EfbaBANI',
    appId: '1:1084451587591:web:505128573d6a676b948ca2',
    messagingSenderId: '1084451587591',
    projectId: 'moca-fmc',
    authDomain: 'moca-fmc.firebaseapp.com',
    storageBucket: 'moca-fmc.appspot.com',
    measurementId: 'G-VQX7P2CEEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2fesJZPwNO5IXaRAXUsK0tre_jD861DY',
    appId: '1:1084451587591:android:ea4a3908cc7e3167948ca2',
    messagingSenderId: '1084451587591',
    projectId: 'moca-fmc',
    storageBucket: 'moca-fmc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq2f-092pM0ohSBRA-5D7YgJg5FfpexcU',
    appId: '1:1084451587591:ios:cc1cbc0c05469405948ca2',
    messagingSenderId: '1084451587591',
    projectId: 'moca-fmc',
    storageBucket: 'moca-fmc.appspot.com',
    iosClientId: '1084451587591-ckopofntb2te7ug0nqlas0n8e8mdel5q.apps.googleusercontent.com',
    iosBundleId: 'com.atinty.moca',
  );
}
